name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:

env:
  MIRROR_URL: 'git@github.com:BryanBole/Chocolatine.git'
  EXECUTABLES: 'mysh'

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run coding style checker
        run: check.sh $(pwd) $(pwd)
  check_program_compilation:
    env:
      EXECUTABLES: ${{ secrets.EXECUTABLES }}
    needs:
      - check_coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make
      timeout-minutes: 2
    - run: make clean
    - run: for FILE in $EXECUTABLES; do test -f $FILE && echo '$FILE exist' ; done
  run_tests:
    needs:
      - check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    timeout-minutes: 2
    steps:
    - uses : actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make tests_run
  push_to_mirror:
    needs: 
      - run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.GIT_SSH_PRIVATE_KEY }}
